# (PART) Getting Started {-}
# Introduction

## Description

Welcome to the PHAC TDU's Data Visualization in R. This course will introduce public health practitioners and field epidemiologists with the skills necessary to use R to creating compelling data visualizations in R in the course of their work. The course consists of two half-day virtual sessions where participants review basic concepts, practice, and reflect upon the use of R to create figures and graphs. This course is oriented to provide epidemiologists and public health practitioners with additional skills and materials for use in the field and is not intended to be comprehensive training on either

1.  Scientific communications (incl. graphic design, or data visualization), or

2.  R overall.

## Prerequisites

Participants should have a background in epidemiology and have previously completed training in public health investigations and surveillance (or equivalent). Participants should also be comfortable performing basic tasks in R, such as **loading**, **reshaping**, and **cleaning** data as well as conducting **descriptive epidemiological analyses**. Please review the [Self-Study Pre-Course Module](https://bit.ly/3EC4bK3) for Introduction to R for Public Health Investigations for a refresher on fundamentals as needed.

## Experiential Aims

1.  For participants to be comfortable practicing the ggplot2 package, facets, and theme functions.
2.  To reinforce and supplement previous Training and Development Unit learning on Scientific Communications (as applicable, not required).
3.  To create a relaxed and safe environment for practice, questions, share-back, and reflection.

## Learning Objectives

By the end of this course, participants will be able to:

1.  Describe the ggplot2 package and its use in creating compelling data visualizations in R.
2.  Use the ggplot2 package to create commonly used figures and graphs.
3.  Apply facets to create multi-panel plots.
4.  Create and apply built-in and user defined themes to figures.
5.  Leverage the functionality of R to apply best practices for accessibility as it relates to data visualization (e.g., colour palettes, whitespace, texture and colour, and labeling).

## Target Audience

Public Health Agency of Canada epidemiologists involved in front-line service delivery, such as field epidemiologists from the Canadian Field Epidemiology Program and Public Health Officers from the Canadian Public Health Service.
