# Training Datasets for use in the course {#datasets}

This chapter will include references to openly available datasets and provide some suggestions for how we can use them.

## Summary of datasets

The following tables provide links to data useful for either public-health based examples, or other fun examples for use. Note that some of these data sets are internal to the TDU and require internal permissions to access. For more information, or if you would like to gain access to an internal training data set, please [contact the TDU](mailto:ceprtraining-formationcmiu@phac-aspc.gc.ca).

Table: (\#tab:phdatasets) Public Health Datasets

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-------------------------------------------------+
| Title                                                                                                                                                                                                                                                                                        | Description                                                                                | Use                                             |
+==============================================================================================================================================================================================================================================================================================+============================================================================================+=================================================+
| [Covid-19 Training Dataset](https://022gc-my.sharepoint.com/:f:/r/personal/joanne_stares_phac-aspc_gc_ca/Documents/CapacityBuilding_DataManagement/DataManagement_3_Excel_pt1?csf=1&web=1&e=6T3a0p "Covid-19 Training Dataset")                                                              | Created by Alex for use in the TDU Data management course in Excel.                        | data-cleaning; epi-curve                        |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-------------------------------------------------+
| [Tiramisu](https://022gc-my.sharepoint.com/:f:/r/personal/joanne_stares_phac-aspc_gc_ca/Documents/IntroToStata/Tira%20Case%20Study?csf=1&web=1&e=Aqo5ge "Tiramisu training data")                                                                                                            | Foodborne training dataset. Originally used for the Introduction to STATA training course. | epi-curve;                                      |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-------------------------------------------------+
| [Chlamydia STI Surveillance](https://022gc-my.sharepoint.com/:f:/r/personal/joanne_stares_phac-aspc_gc_ca/Documents/IntroToStata/Chlamydia%20Case%20Study?csf=1&web=1&e=6S885y "Chlamydia case study")                                                                                       | From Intro to STATA training course.                                                       | contact-tracing; data-linking; epi-curve; rates |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-------------------------------------------------+
| [Opioid and Stimulant related harms](https://open.canada.ca/data/en/dataset/1092497d-6c72-4e66-930b-9d6337e64af5 "Opioid and Stimulant related harms")                                                                                                                                       | GoC Open-data portal                                                                       | bar-graph; rates; regional                      |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-------------------------------------------------+
| Canada Notifiable Disease Surveillance System [(1)](https://open.canada.ca/data/en/dataset/b712dd07-f30d-463f-b743-26ab3465d91b "CNDSS Link 1"); [(2)](https://open.canada.ca/data/en/dataset/f2a711f9-be80-4b98-a205-8ac9e5e0d126 "CNDSS Link 2")                                           | GoC Open-data portal                                                                       | bar-graph; rates; regional                      |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-------------------------------------------------+
| [Canada Public Health Infobase](https://health-infobase.canada.ca/ "CPHI Link")                                                                                                                                                                                                              |                                                                                            |                                                 |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-------------------------------------------------+
| [Canada Substance Use and Harms Database](https://csuch.ca/explore-the-data/)                                                                                                                                                                                                                |                                                                                            |                                                 |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-------------------------------------------------+
| R4Epi Ebola Outbreak linelist: ([Raw](https://github.com/appliedepi/epirhandbook_eng/raw/master/data/case_linelists/linelist_raw.xlsx "R4Epi Ebola Raw")); ([Clean](https://github.com/appliedepi/epirhandbook_eng/raw/master/data/case_linelists/linelist_cleaned.rds "R4Epi Ebola Clean")) | Fictional Ebola Outbreak from the R4Epi Handbook                                           | epi-curve; rates; regional                      |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------+-------------------------------------------------+


The next table summarizes data sets that do not contain public-health related data specifically, but may still provide for fun data visualization examples. 


Table: (\#tab:fundatasets) Non-Public Health Datasets

+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+------------------------+
| Title                                                                                  | Description                                                                                            | Use                    |
+========================================================================================+========================================================================================================+========================+
| [Palmer's Penguins](https://allisonhorst.github.io/palmerpenguins/ "Penguin Datasets") | Data on 344 penguins collected from antarctic research station. Data include measurements and species. | scatterplot; bar-graph |
+----------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+------------------------+

#### Placeholder references:

Table \@ref(tab:phdatasets)

Table \@ref(tab:fundatasets)
