# (PART) Learning Modules {.unnumbered}

# Formatting your data

## Installing Tidyverse

Even though this course is about data visualizations, we still have to talk about formatting data effectively before using them to create nice graphics and visuals!

For all of our data formatting examples, we'll be using packages native to the [Tidyverse](https://www.tidyverse.org/).

Chances are, if you've gotten this far, then you already have the Tidyverse library installed on your computer! However, if you've somehow managed to sneak your way into the course and through the first couple chapters without installing it, then now is the time to do so!

You can install the tidyverse on your computer by writing the following code into your R console and hitting enter:

> install.packages("tidyverse")

Once you've done that, you'll need to load the library to access all of the very helpful included packages and functions! Do this using the command:

> library(tidyverse)

Note that when you're installing the package, the package name must be wrapped in quotation marks. However, when you're activating the package using the `library()` command, you don't need to use quotes.

## Loading an example dataset

For the following example, we'll use the data set "Palmer's Penguins." More information about this data set can be found in Table \@ref(tab:fundatasets).
